# Generated by Django 5.2.9 on 2025-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachments',
            field=models.FileField(blank=True, help_text='Supporting documents', null=True, upload_to='claim_attachments/'),
        ),
    ]
