# Generated by Django 5.2.9 on 2025-12-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status_note',
            field=models.TextField(blank=True, help_text='Reason or note for the latest status change'),
        ),
    ]
