# Generated by Django 5.2.9 on 2025-12-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(help_text='Unique payment reference number', max_length=50, unique=True)),
                ('due_date', models.DateField(help_text='When this payment is due')),
                ('paid_date', models.DateField(blank=True, help_text='When payment was actually made', null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount to be paid', max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('CHECK', 'Check')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank/gateway transaction ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operations.policy')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
