# Generated by Django 5.2.9 on 2025-12-16 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_premiumpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'Standard 2% Monthly Late Charge'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('DAYS_OVERDUE', 'Days Overdue'), ('MONTHS_OVERDUE', 'Months Overdue')], default='DAYS_OVERDUE', max_length=20)),
                ('trigger_threshold', models.IntegerField(help_text='Days or months threshold before charge applies')),
                ('charge_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Payment Amount'), ('FLAT', 'Flat Fee')], max_length=20)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 2.5 for 2.5%) or flat amount (e.g., 50.00)', max_digits=10)),
                ('maximum_charge_per_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on total late charge per payment (optional)', max_digits=12, null=True)),
                ('applies_to_all_policies', models.BooleanField(default=True, help_text='If False, manually select which policies use this')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_late_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Late Charge Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LateCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Late charge amount', max_digits=10)),
                ('reason', models.CharField(default='Late Payment Charge', help_text='Why this charge was applied', max_length=200)),
                ('is_paid', models.BooleanField(default=False, help_text='Has the late charge been paid?')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin can add notes about this charge')),
                ('waived', models.BooleanField(default=False, help_text='Admin can waive the charge')),
                ('waived_reason', models.TextField(blank=True)),
                ('waived_date', models.DateField(blank=True, null=True)),
                ('payment', models.OneToOneField(help_text='Payment this charge is applied to', on_delete=django.db.models.deletion.CASCADE, related_name='late_charge', to='operations.premiumpayment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_charges', to='operations.policy')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_late_charges', to=settings.AUTH_USER_MODEL)),
                ('charge_policy', models.ForeignKey(blank=True, help_text='Which policy generated this charge (can be null if manually created)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.latechargepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('payment', 'policy')},
            },
        ),
    ]
