# Generated by Django 5.2.9 on 2025-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('NOTE', 'Note')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(help_text='Referral, Website, etc.', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost'), ('CONVERTED', 'Converted')], default='NEW', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Opportunity Name (e.g. 'Cyber Insurance 2025')", max_length=200)),
                ('stage', models.CharField(choices=[('DISCOVERY', 'Discovery'), ('QUOTE', 'Quote Sent'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='DISCOVERY', max_length=20)),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
