# Generated by Django 5.2.9 on 2025-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(default=25, help_text='Win probability percentage (0-100)'),
        ),
    ]
