# Generated by Django 5.2.9 on 2025-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(blank=True, help_text='Original statement file', null=True, upload_to='statements/'),
        ),
    ]
