# Generated by ChatGPT on 2026-02-04
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_latechargepolicy_latecharge'),
        ('reconciliation', '0002_bankstatement_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Insurer ABC - Jan 2025 Brokerage', max_length=255)),
                ('insurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, help_text='Original statement file', null=True, upload_to='brokerage_statements/')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('brokerage_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Brokerage %', max_digits=6, null=True)),
                ('brokerage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_brokerage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('VARIANCE', 'Variance'), ('APPROVED', 'Approved'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approval_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_brokerage_lines', to=settings.AUTH_USER_MODEL)),
                ('matched_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokerage_lines', to='operations.policy')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation.brokeragestatement')),
            ],
        ),
    ]
